server:
  port: 8899
  address: 0.0.0.0
  name: go-cheetah-admin
  # # 生产环境建议使用 release，debug：可以使用debug模式
  model: debug
  adminUser: admin
  adminPwd: 50c0a53b7a562ca8156bf86c20ca4f75
  # 仅支持 mysql、sqlite,默认为sqlite
  dbDriver: mysql

# 数据库配置
mysql:
  DbHost: 127.0.0.1
  DbPort: 3306
  # 数据库名称 需要提前创建好
  DbName: go-cheetah-admin
  DbUser: root
  DbPwd: zxl@2025
  MaxIdleConns: 10
  MaxOpenConns: 100
  # 是否开启debug，1 开启 0 关闭
  ActiveDebug: 1

sqlite:
  # 名称不建议修改
  DbName: go-cheetah-admin.db
  ActiveDebug: 0

# 密码加密
aes:
  key: go-cheetah-admin

jwt:
  realm: go-cheetah-admin
  # jwt加密因子
  key: anruo
  #  jwt token过期时间 单位为小时
  timeout: 100
  # jwt token刷新时间 单位为小时
  maxRefresh: 1